### ISSUE TITLE
Could not open file branch-name:composer.lock or find it in git as branch-name:composer.lock: fatal: invalid object name 'branch-name'

### ISSUE THREAD

**Issue by janedbal** [IonBazan/composer-diff#30] opened 2024-02-22 16:45 UTC
See job output: https://github.com/qossmic/deptrac/actions/runs/8007789467/job/21872726582?pr=1374

```
In PackageDiff.php line 136:
                                                                               
  [RuntimeException]                                                           
  Could not open file composer-dependency-analyser:composer.lock or find it i  
  n git as composer-dependency-analyser:composer.lock: fatal: invalid object   
  name 'composer-dependency-analyser'.                                         
                                                                               

Exception trace:
  at /workdir/vendor/ion-bazan/composer-diff/src/PackageDiff.php:136
 IonBazan\ComposerDiff\PackageDiff->getFileContents() at /workdir/vendor/ion-bazan/composer-diff/src/PackageDiff.php:92
 IonBazan\ComposerDiff\PackageDiff->loadPackages() at /workdir/vendor/ion-bazan/composer-diff/src/PackageDiff.php:79
 IonBazan\ComposerDiff\PackageDiff->getPackageDiff() at /workdir/vendor/ion-bazan/composer-diff/src/Command/DiffCommand.php:141
 IonBazan\ComposerDiff\Command\DiffCommand->execute() at /workdir/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /workdir/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /workdir/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /workdir/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /workdir/vendor/ion-bazan/composer-diff/composer-diff:[30](https://github.com/qossmic/deptrac/actions/runs/8007723786/job/21872510353?pr=1374#step:4:31)
 include() at /workdir/vendor/bin/composer-diff:120
```

Maybe related to the fact that [the newly added package](https://github.com/shipmonk-rnd/composer-dependency-analyser) in [the PR](https://github.com/qossmic/deptrac/pull/1374) has `composer.lock` committed and not `export-ignore`d in `.gitattributes`, but I'm guessing here.

**Comment by IonBazan** [comment] 2024-02-23 03:26
@janedbal I think this action: [WyriHaximus/github-action-composer.lock-diff](https://github.com/WyriHaximus/github-action-composer.lock-diff) is not resolving the HEAD branch correctly and as far as I can see, it doesn't allow to customize it. Can you try with the action I created: https://github.com/marketplace/actions/composer-diff? It allows to customize the target and base branch, but I recommend leaving them at default settings. I'm using the same action in my other projects and they are working fine.

**Comment by IonBazan** [comment] 2024-02-25 15:02
Closing as it looks that it's not caused by this package. Please feel free to reopen this issue if needed.

**Closed by IonBazan** 2024-02-25 15:02 UTC

**Comment by janedbal** [comment] 2024-02-25 17:01
Maybe the error message can be improved here?

**Comment by WyriHaximus** [comment] 2024-03-05 15:36
@IonBazan Turned out the issue was in @janedbal using v1 which is indeed broken for PR's. v2 does not have that issue because it's using the checkout actions internally. Just added reasoning to my action's readme with the difference between yours and mine: https://github.com/WyriHaximus/github-action-composer.lock-diff?tab=readme-ov-file#reasoning

**Comment by IonBazan** [comment] 2024-03-05 16:36
@WyriHaximus that explains a lot! Thanks for updating the readme and helping us with the issue. Let me know if you have any ideas or improvements for the action I created, feel free to propose PRs there too.
